name: java-build-push
'on': [push]
jobs:
  build-binaries:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'adopt'
      - name: Compile java files
        run: cd src && javac -d ../out xt/surge/swingset/Main.java
      - name: Create JAR file
        run: cd out && jar -cmvf ../manifest.txt swingset-bleeding-edge.jar ../res xt
